# Generated by Django 4.0.5 on 2022-06-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('preferred_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.language')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.user')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDisplayName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.language')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('role_name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=2000, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.user')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('about_me', models.CharField(max_length=2000, null=True)),
                ('about_me_language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.user')),
            ],
        ),
    ]
