# Generated by Django 4.0.5 on 2022-06-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skilldisplayname',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='userlanguage',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.language'),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('role_name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.company')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbuilder.user')),
            ],
        ),
    ]
