# Generated by Django 4.0.5 on 2022-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_remove_cv_end_date_remove_cv_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
