# Generated by Django 4.0.5 on 2022-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0004_alter_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='company',
            field=models.CharField(max_length=200),
        ),
    ]
